Updated db-worker.js
dsych/next pull request #1
Opened 2018-05-23 18:29 UTC by Fatehsandhu

Added basic routing stubs

2018-05-23 23:10 UTC, dsych commented
@Fatehsandhu this PR will be on hold until [this PR](https://github.com/mischnic/parcel-plugin-sw-cache/pull/11) has landed for the parcel-workbox plugin.

2018-05-23 23:12 UTC, dsych requested changes

2018-05-23 23:12 UTC, dsych commented on src/db-worker.js
> +workbox.routing.registerRoute(/\b(io\/from\/dataurl|io\/in|io\/share|io\/archive|terminal|io\/reset).*/,
We should stay away from declaring static routes unless they are needed to be accessed like a rest API. Instead, I suggest we leverage  [parcel workbox plugin](https://github.com/mischnic/parcel-plugin-sw-cache) and define our routes inside package.json, so that they are injected alongside other precache routes for the db.

2018-05-23 23:20 UTC, Fatehsandhu commented on src/db-worker.js
> +workbox.routing.registerRoute(/\b(io\/from\/dataurl|io\/in|io\/share|io\/archive|terminal|io\/reset).*/,
@dsych How do we do that?
is it something like this? 
```js
"runtimeCaching": [
    {
        "urlPattern": ["my-match\/api\.[0-9]+", "i"]
    }
```

2018-05-23 23:48 UTC, dsych commented on src/db-worker.js
> +workbox.routing.registerRoute(/\b(io\/from\/dataurl|io\/in|io\/share|io\/archive|terminal|io\/reset).*/,
Are you trying to precache those files? Because the strategy that you are using is going to check cache first, and then go to network if files do not exists. they will only exist, if you requested them earlier or user have already navigated to the page.

2018-05-24 15:53 UTC, dsych commented
@Fatehsandhu for the time being I guess we can leave them as dynamic cache and revisit later.

2018-05-24 15:54 UTC, merged